DROP TABLE IF EXISTS Permission;

CREATE TABLE Permission (
    role VARCHAR(14),
    manipulator VARCHAR(6),
    model VARCHAR(16),
    PRIMARY KEY (role, manipulator, model)
);

GRANT UPDATE, INSERT, DELETE ON Permission TO 'root'@'localhost';

INSERT INTO Permission
VALUES 
('Lecturer', 'INSERT', 'Author'),
('Lecturer', 'DELETE', 'Author'),
('Lecturer', 'UPDATE', 'Author'),
('AAOStaff', 'SELECT', 'Author'),
('FacultyOfficer', 'SELECT', 'Author'),
('Lecturer', 'SELECT', 'Author'),
('Student', 'SELECT', 'Author'),

('AAOStaff', 'INSERT', 'Class'),
('AAOStaff', 'DELETE', 'Class'),
('AAOStaff', 'UPDATE', 'Class'),
('FacultyOfficer', 'UPDATE', 'Class'),
('AAOStaff', 'SELECT', 'Class'),
('FacultyOfficer', 'SELECT', 'Class'),
('Lecturer', 'SELECT', 'Class'),
('Student', 'SELECT', 'Class'),


('FacultyOfficer', 'INSERT', 'ContactAddress'),
('FacultyOfficer', 'DELETE', 'ContactAddress'),
('FacultyOfficer', 'UPDATE', 'ContactAddress'),
('AAOStaff', 'SELECT', 'ContactAddress'),
('FacultyOfficer', 'SELECT', 'ContactAddress'),
('Lecturer', 'SELECT', 'ContactAddress'),
('Student', 'SELECT', 'ContactAddress'),

('AAOStaff', 'INSERT', 'Faculty'),
('AAOStaff', 'DELETE', 'Faculty'),
('AAOStaff', 'UPDATE', 'Faculty'),
('AAOStaff', 'SELECT', 'Faculty'),
('FacultyOfficer', 'SELECT', 'Faculty'),
('Lecturer', 'SELECT', 'Faculty'),
('Student', 'SELECT', 'Faculty'),

('AAOStaff', 'INSERT', 'FacultyStaff'),
('FacultyOfficer', 'INSERT', 'FacultyStaff'),
('AAOStaff', 'DELETE', 'FacultyStaff'),
('FacultyOfficer', 'DELETE', 'FacultyStaff'),
('AAOStaff', 'UPDATE', 'FacultyStaff'),
('FacultyOfficer', 'UPDATE', 'FacultyStaff'),
('Lecturer', 'UPDATE', 'FacultyStaff'),
('AAOStaff', 'SELECT', 'FacultyStaff'),
('FacultyOfficer', 'SELECT', 'FacultyStaff'),
('Lecturer', 'SELECT', 'FacultyStaff'),
('Student', 'SELECT', 'FacultyStaff'),

('AAOStaff', 'INSERT', 'FacultyOfficer'),
('FacultyOfficer', 'INSERT', 'FacultyOfficer'),
('AAOStaff', 'DELETE', 'FacultyOfficer'),
('FacultyOfficer', 'DELETE', 'FacultyOfficer'),
('AAOStaff', 'UPDATE', 'FacultyOfficer'),
('FacultyOfficer', 'UPDATE', 'FacultyOfficer'),
('AAOStaff', 'SELECT', 'FacultyOfficer'),
('FacultyOfficer', 'SELECT', 'FacultyOfficer'),
('Lecturer', 'SELECT', 'FacultyOfficer'),
('Student', 'SELECT', 'FacultyOfficer'),

('AAOStaff', 'INSERT', 'Learn'),
('AAOStaff', 'DELETE', 'Learn'),
('AAOStaff', 'UPDATE', 'Learn'),
('AAOStaff', 'SELECT', 'Learn'),
('FacultyOfficer', 'SELECT', 'Learn'),
('Lecturer', 'SELECT', 'Learn'),
('Student', 'SELECT', 'Learn'),

('AAOStaff', 'INSERT', 'Lecturer'),
('FacultyOfficer', 'INSERT', 'Lecturer'),
('AAOStaff', 'DELETE', 'Lecturer'),
('FacultyOfficer', 'DELETE', 'Lecturer'),
('AAOStaff', 'UPDATE', 'Lecturer'),
('FacultyOfficer', 'UPDATE', 'Lecturer'),
('Lecturer', 'UPDATE', 'Lecturer'),
('AAOStaff', 'SELECT', 'Lecturer'),
('FacultyOfficer', 'SELECT', 'Lecturer'),
('Lecturer', 'SELECT', 'Lecturer'),
('Student', 'SELECT', 'Lecturer'),

('Lecturer', 'INSERT', 'Publisher'),
('Lecturer', 'DELETE', 'Publisher'),
('Lecturer', 'UPDATE', 'Publisher'),
('AAOStaff', 'SELECT', 'Publisher'),
('FacultyOfficer', 'SELECT', 'Publisher'),
('Lecturer', 'SELECT', 'Publisher'),
('Student', 'SELECT', 'Publisher'),

('Student', 'INSERT', 'Register'),
('AAOStaff', 'DELETE', 'Register'),
('Student', 'DELETE', 'Register'),
('AAOStaff', 'UPDATE', 'Register'),
('Student', 'UPDATE', 'Register'),
('AAOStaff', 'SELECT', 'Register'),
('FacultyOfficer', 'SELECT', 'Register'),
('Lecturer', 'SELECT', 'Register'),
('Student', 'SELECT', 'Register'),

('AAOStaff', 'INSERT', 'Semester'),
('AAOStaff', 'DELETE', 'Semester'),
('AAOStaff', 'UPDATE', 'Semester'),
('AAOStaff', 'SELECT', 'Semester'),
('FacultyOfficer', 'SELECT', 'Semester'),
('Lecturer', 'SELECT', 'Semester'),
('Student', 'SELECT', 'Semester'),

('AAOStaff', 'INSERT', 'Staff'),
('AAOStaff', 'DELETE', 'Staff'),
('AAOStaff', 'UPDATE', 'Staff'),
('FacultyOfficer', 'UPDATE', 'Staff'),
('Lecturer', 'UPDATE', 'Staff'),
('AAOStaff', 'SELECT', 'Staff'),
('FacultyOfficer', 'SELECT', 'Staff'),
('Lecturer', 'SELECT', 'Staff'),
('Student', 'SELECT', 'Staff'),

('AAOStaff', 'INSERT', 'Student'),
('AAOStaff', 'DELETE', 'Student'),
('AAOStaff', 'UPDATE', 'Student'),
('Student', 'UPDATE', 'Student'),
('AAOStaff', 'SELECT', 'Student'),
('FacultyOfficer', 'SELECT', 'Student'),
('Lecturer', 'SELECT', 'Student'),
('Student', 'SELECT', 'Student'),

('FacultyOfficer', 'INSERT', 'Subject'),
('FacultyOfficer', 'DELETE', 'Subject'),
('FacultyOfficer', 'UPDATE', 'Subject'),
('AAOStaff', 'SELECT', 'Subject'),
('FacultyOfficer', 'SELECT', 'Subject'),
('Lecturer', 'SELECT', 'Subject'),
('Student', 'SELECT', 'Subject'),

('AAOStaff', 'INSERT', 'Teach'),
('AAOStaff', 'DELETE', 'Teach'),
('AAOStaff', 'UPDATE', 'Teach'),
('AAOStaff', 'SELECT', 'Teach'),
('FacultyOfficer', 'SELECT', 'Teach'),
('Lecturer', 'SELECT', 'Teach'),
('Student', 'SELECT', 'Teach'),

('Lecturer', 'INSERT', 'Textbook'),
('Lecturer', 'DELETE', 'Textbook'),
('Lecturer', 'UPDATE', 'Textbook'),
('AAOStaff', 'SELECT', 'Textbook'),
('FacultyOfficer', 'SELECT', 'Textbook'),
('Lecturer', 'SELECT', 'Textbook'),
('Student', 'SELECT', 'Textbook'),

('Lecturer', 'INSERT', 'TextbookCategory'),
('Lecturer', 'DELETE', 'TextbookCategory'),
('Lecturer', 'UPDATE', 'TextbookCategory'),
('AAOStaff', 'SELECT', 'TextbookCategory'),
('FacultyOfficer', 'SELECT', 'TextbookCategory'),
('Lecturer', 'SELECT', 'TextbookCategory'),
('Student', 'SELECT', 'TextbookCategory'),

('Lecturer', 'INSERT', 'UseFor'),
('Lecturer', 'DELETE', 'UseFor'),
('Lecturer', 'UPDATE', 'UseFor'),
('AAOStaff', 'SELECT', 'UseFor'),
('FacultyOfficer', 'SELECT', 'UseFor'),
('Lecturer', 'SELECT', 'UseFor'),
('Student', 'SELECT', 'UseFor'),

('AAOStaff', 'INSERT', 'User'),
('FacultyOfficer', 'INSERT', 'User'),
('Lecturer', 'INSERT', 'User'),
('Student', 'INSERT', 'User'),
('AAOStaff', 'DELETE', 'User'),
('FacultyOfficer', 'DELETE', 'User'),
('Lecturer', 'DELETE', 'User'),
('Student', 'DELETE', 'User'),
('AAOStaff', 'UPDATE', 'User'),
('FacultyOfficer', 'UPDATE', 'User'),
('Lecturer', 'UPDATE', 'User'),
('Student', 'UPDATE', 'User'),
('AAOStaff', 'SELECT', 'User'),
('FacultyOfficer', 'SELECT', 'User'),
('Lecturer', 'SELECT', 'User'),
('Student', 'SELECT', 'User'),

('AAOStaff', 'INSERT', 'UserPhone'),
('FacultyOfficer', 'INSERT', 'UserPhone'),
('Lecturer', 'INSERT', 'UserPhone'),
('Student', 'INSERT', 'UserPhone'),
('AAOStaff', 'DELETE', 'UserPhone'),
('FacultyOfficer', 'DELETE', 'UserPhone'),
('Lecturer', 'DELETE', 'UserPhone'),
('Student', 'DELETE', 'UserPhone'),
('AAOStaff', 'UPDATE', 'UserPhone'),
('FacultyOfficer', 'UPDATE', 'UserPhone'),
('Lecturer', 'UPDATE', 'UserPhone'),
('Student', 'UPDATE', 'UserPhone'),
('AAOStaff', 'SELECT', 'UserPhone'),
('FacultyOfficer', 'SELECT', 'UserPhone'),
('Lecturer', 'SELECT', 'UserPhone'),
('Student', 'SELECT', 'UserPhone'),

('AAOStaff', 'INSERT', 'ClassTime'),
('AAOStaff', 'DELETE', 'ClassTime'),
('AAOStaff', 'UPDATE', 'ClassTime'),
('AAOStaff', 'SELECT', 'ClassTime'),
('FacultyOfficer', 'SELECT', 'ClassTime'),
('Lecturer', 'SELECT', 'ClassTime'),
('Student', 'SELECT', 'ClassTime'),

('FacultyOfficer', 'INSERT', 'Manage'),
('FacultyOfficer', 'DELETE', 'Manage'),
('FacultyOfficer', 'UPDATE', 'Manage'),
('AAOStaff', 'SELECT', 'Manage'),
('FacultyOfficer', 'SELECT', 'Manage'),
('Lecturer', 'SELECT', 'Manage'),
('Student', 'SELECT', 'Manage'),

('FacultyOfficer', 'INSERT', 'OpenedIn'),
('FacultyOfficer', 'DELETE', 'OpenedIn'),
('FacultyOfficer', 'UPDATE', 'OpenedIn'),
('AAOStaff', 'SELECT', 'OpenedIn'),
('FacultyOfficer', 'SELECT', 'OpenedIn'),
('Lecturer', 'SELECT', 'OpenedIn'),
('Student', 'SELECT', 'OpenedIn');
